spring:
  application:
    name: center
#--------------------peer1的配置----------------------------------
---
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    instance-id: eureka-peer1:8761
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
      ##defaultZone: http://47.98.140.228:8762/eureka/
#    fetch-registry: false
#    register-with-eureka: false
#  server:
#    enable-self-preservation: false #关闭自我保护模式
spring:
  profiles: peer1
#---------------------peer2的配置-----------------------------------------
---
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: eureka-peer2:8762
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#    register-with-eureka: false
#    fetch-registry: false
#  server:
#    enable-self-preservation: false
server:
  port: 8762
spring:
  profiles: peer2
