spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jimboLix/configServer
          username: lrhtomcat@163.com
          password: 
          basedir: /tmp/configRep
  rabbitmq:
    host: 47.98.140.228
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
#      defaultZone: http://47.98.140.228:8762/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    hostname: config-server
    instance-id: config-server
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"




